---
- name: download Hadoop release {{ hadoop_release }}
  get_url: url='http://ftp.ps.pl/pub/apache/hadoop/core/{{ hadoop_release }}/{{ hadoop_archive }}'
           dest='/home/vagrant/{{ hadoop_archive }}'
           sha256sum='{{ hadoop_sha256 }}'

- name: extract Hadoop archive
  command: tar xzf '/home/vagrant/{{ hadoop_archive }}'
           chdir=/home/vagrant/
           creates='{{ hadoop_home_dir }}'

- name: symlink Hadoop home directory to just hadoop/
  file: path=/home/vagrant/hadoop src='{{ hadoop_home_dir }}' state=link

- name: add HADOOP_PREFIX to environment variables
  lineinfile: dest=~/.bash_profile
              regexp=^HADOOP_PREFIX=
              line=HADOOP_PREFIX={{ hadoop_home_dir }}
              create=yes

- name: set JAVA_HOME environment variable for Hadoop
  lineinfile: dest='{{ hadoop_home_dir }}/etc/hadoop/hadoop-env.sh'
              regexp='^#?\s*export JAVA_HOME='
              line='export JAVA_HOME=/usr/lib/jvm/java-7-oracle/jre'
              state=present

- name: write Hadoop core config file
  template: src=hadoop-core-site.xml.j2
            dest='{{ hadoop_home_dir }}/etc/hadoop/core-site.xml'

- name: write Hadoop HDFS config file
  template: src=hadoop-hdfs-site.xml.j2
            dest='{{ hadoop_home_dir }}/etc/hadoop/hdfs-site.xml'

- name: format the Hadoop filesystem
  command: ./bin/hdfs namenode -format
           chdir={{ hadoop_home_dir }}
           creates={{ hadoop_tmp_dir }}

- name: start Hadoop DFS daemons
  command: ./sbin/start-dfs.sh
           chdir={{ hadoop_home_dir }}
  register: hadoop_start
  changed_when: hadoop_start.stdout.find('starting datanode') == -1
